BASE = 0

STARTOFFSET = 5
BASEOFFSET = 17
BOARDLENGTH = BASEOFFSET*4
HOMEPATHLENGTH = 8
HOME = BOARDLENGTH + HOMEPATHLENGTH

RED = 'RED'
BLUE = 'BLUE'
YELLOW = 'YELLOW'
GREEN = 'GREEN'
COLORS = [RED, BLUE, YELLOW, GREEN]

START_ROLL = 5