BASE = 0

STARTOFFSET = 5
BASEOFFSET = 17
BOARDLENGTH = BASEOFFSET*4
HOMEPATHLENGTH = 8
HOME = BOARDLENGTH + HOMEPATHLENGTH

SAFE_POSITIONS = [0, 5, 12, 17, 22, 29, 34, 39, 46, 51, 56, 63]

RED = 'RED'
BLUE = 'BLUE'
YELLOW = 'YELLOW'
GREEN = 'GREEN'
COLORS = [RED, BLUE, YELLOW, GREEN]

START_ROLL = 5

